#! /usr/bin/env bash
# list users by memory and CPU usage so that you know whom to blame in a busy computer
# Song Qiang <keeyang@ustc.edu> 2017

(
echo "USER #Proc %CPU %MEM"
echo "-------- ----- ---- ----"
ps aux|awk '
NR == 1 {
    cpu["TOTAL"] = 0;
    mem["TOTAL"] = 0;
    process["TOTAL"] = 0;
}

NR > 1 {
    cpu["TOTAL"] += $3;
    mem["TOTAL"] += $4;
    process["TOTAL"] += 1;

    if ($1 in mem) {
        cpu[$1] += $3;
        mem[$1] += $4;
        process[$1] += 1;
    } else {
        cpu[$1] = $3;
        mem[$1] = $4;
        process[$1] = 1;
    }
}

END {
        for (user in mem) {
        print user,process[user],cpu[user],mem[user];
    }
}
'|sort -k4,4gr -k3,3gr -k2,2gr
) |column -t
